### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by ghost** [pirate/crypto-trader#6]
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gemini_api as api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jimmyok/bot/crypto-trader/gemini_api.py", line 47
    print(f'Rate limit exceeded! Retrying in 10 seconds...')
                                                          ^
SyntaxError: invalid syntax

**Comment by jerthom** [comment]
This seems to be a user error, not an issue. Python f strings were [introduced in 3.6](https://www.python.org/dev/peps/pep-0498/) and you're saying that you're using 3.4.2.  The developer info section of the readme states "This library is built on Python 3.6". Try upgrading to 3.6 and running again.
